### PR TITLE
Use HTTPS where possible

### PR DESCRIPTION
**Pull request by qgustavor**

### CODE REVIEW

**Review by iphands — COMMENTED** [review]
Sorry its been so damn long. I'll change if you dont want to but I'd prefer to use :// rather than https://
Does that work for you?

**Comment by qgustavor** [comment]
Do you mean `//`? ["This technique is now an anti-pattern"](https://www.paulirish.com/2010/the-protocol-relative-url/).

**Comment by iphands** [comment]
Fair enough!
Merging, sorry for the two year wait. I suck O_o

**Comment by qgustavor** [comment]
No problem.

**Pull request merged**
